CREATE TABLE [dbo].[Todo]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_tODO PRIMARY KEY DEFAULT NEWID(),
    [Title] NVARCHAR(255) NOT NULL,
    [IsDone] BIT NOT NULL CONSTRAINT DF_Todo_IsDone DEFAULT 0,
    [CreatedAt] DATETIME2 NOT NULL DEFAULT GETDATE(),

    );